### ISSUE TITLE
No ESR generated

### ISSUE THREAD

**Issue by tttttx2** [OCA/l10n-switzerland#254] opened 2016-08-08 12:44 UTC
Hi There
I have a little issue with the payment slip module.
All the Invoices I recently generated are missing the ESR number. If I try to add one manually I always get the following error message. Can you help me, please?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 5198, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 3190, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/models.py", line 5653, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/fields.py", line 835, in __get__
    self.determine_value(record)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/fields.py", line 937, in determine_value
    self.compute_value(recs)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/fields.py", line 893, in compute_value
    self._compute_value(records)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/fields.py", line 885, in _compute_value
    self.compute(records)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/l10n_ch_payment_slip/payment_slip.py", line 868, in draw_payment_slip_image
    img = self._draw_payment_slip()
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/l10n_ch_payment_slip/payment_slip.py", line 804, in _draw_payment_slip
    default_font, com_partner)
  File "/usr/local/lib/python2.7/dist-packages/odoo-8.0-py2.7.egg/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/lib/odoo/.local/share/Odoo/addons/8.0/l10n_ch_payment_slip/payment_slip.py", line 481, in _draw_address
    text.textOut(com_partner.name)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfgen/textobject.py", line 423, in textOut
    self._x = self._x + self._canvas.stringWidth(text, self._fontname, self._fontsize)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfgen/canvas.py", line 1672, in stringWidth
    (fontSize,self._fontsize)[fontSize is None])
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/pdfmetrics.py", line 720, in stringWidth
    return getFont(fontName).stringWidth(text, fontSize, encoding=encoding)
  File "/usr/lib/python2.7/dist-packages/reportlab/pdfbase/ttfonts.py", line 1137, in stringWidth
    return instanceStringWidthTTF(self,text,size,encoding)
  File "/build/python-reportlab-r6mGL1/python-reportlab-3.3.0/src/rl_addons/rl_accel/_rl_accel.c", line 857, in instanceStringWidthTTF
AttributeError: decode
```

**Comment by yvaucher** [comment] 2016-11-16 16:20
This seems to be an error of encoding with the partner name. What kind of special characters did you had in this string to generate such error ?

**Comment by tttttx2** [comment] 2016-11-16 16:28
I'm sorry, I don't remember exactly. But most likely some Umlaut (ä ö ü) as those are very common in the german language.
The strange thing however was, that it affected all of my invoices, no matter which partner I used.

**Comment by yvaucher** [comment] 2016-11-16 17:58
@tttttx2 Did you solve it?

I cannot reproduce on Odoo 9.0
I tried with ä ö ü in the customer name

By the way my python-reportlab version is:

reportlab==3.1.44

**Comment by tttttx2** [comment] 2016-11-16 18:41
@yvaucher Yes and no. I now generate the esr number by myself. So the issue is fixed in my case, but only with a very nasty workaround. (Odoo python action on invoice generation and a custom diy module to compute the checksums.)

Don't know the reportlab version, but I was using the odoo 8.0 nightly repository at that time.

**Comment by yvaucher** [comment] 2016-11-16 19:04
Looking at your logs your report-lab version is: reportlab-3.3.0

You should be able to find it's version in /usr/lib/python2.7/dist-packages/

**Comment by tttttx2** [comment] 2016-11-16 19:06
Thanks, but unfortunately I'm not quite sure what to do with that information...
Sorry, I am still pretty new to odoo.

**Comment by yvaucher** [comment] 2016-11-16 19:09
Okay I found what could be your error, but I'm not sure how you got there.

I have the same error if my partner has no name (if I bypass the SQL constraint that defines name is required). Did you used some kind of module like partner_firstname that change `res.partner` `name` field ?

**Comment by tttttx2** [comment] 2016-11-16 19:19
I have not actively changed it, no. However I am using the magento odoo bridge from webkul, maybe this could be the cause? I don't have empty name fields in odoo though.

PS: I can not directly attach the module here because it is not free...

**Comment by yvaucher** [comment] 2016-11-17 12:28
@tttttx2 You should be allowed to give the code or part of it as you are on **odoo 8.0** and the license of version 8.0 **must be AGPL** otherwise webkul is violating the AGPL license
(paid module != proprietary module)

https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLAllowMoney
https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLAllowNDA

And AGPL license gives you the right to redistribute the code. An NDA is not compatible with an AGPL module.

Anyway, what you might want to check if you have access to your database is that your table res_partner has no empty cell in `name` column

**Comment by tttttx2** [comment] 2016-11-17 13:06
Thanks for the explanation about the license. Still, I would feel better to not publish their code. If you need it however, I'll be happy to send it to you in private.
(The code I'm talking about is not a change of the odoo source code but it is a module they developed. Can't they choose their own license for their modules?)

I do have access to the database and will check this. Thank you.

**Comment by yvaucher** [comment] 2017-11-03 10:56
This seems a very specific issue depending on other modules. As I'm not able to help further here, I close this issue.

**Closed as completed by yvaucher** 2017-11-03 10:56 UTC
